# Generated by Django 5.0 on 2023-12-19 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end_time',
            new_name='finish_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default='2023-12-19'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='open_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.stage'),
        ),
    ]
