# Generated by Django 5.0 on 2023-12-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_booking_finish_time_alter_booking_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date', 'start_time', 'active']},
        ),
        migrations.AddField(
            model_name='booking',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
