# Generated by Django 5.0 on 2023-12-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_booking_active_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='services',
            field=models.ManyToManyField(related_name='stages', to='api.service'),
        ),
    ]
