# Generated by Django 5.0 on 2023-12-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_service_stage_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='close_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='stage',
            name='open_time',
            field=models.TimeField(),
        ),
    ]
