# Generated by Django 5.0 on 2023-12-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_stage_close_time_alter_stage_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='services',
            field=models.ManyToManyField(related_name='service', to='api.service'),
        ),
    ]
